### ISSUE TITLE
Kolla att Supplement Reglementesdel täcks

### ISSUE THREAD

**Issue by sm5phu** [SverigesSandareamatorer/SSA-Akademin#193]
http://www.ssa.se/download/sektioner/utbildning/Supplement-till-SSA-Utbildningsmaterial-Reglementesdel.pdf

> MOD EDIT:

# ToDo 

Analys visar att det mesta täcks in. Några begrepp förklaras inte i Koncept.
 - [x] Internationella nödsignaler, **13.4**
 - [x] Nödsignaler vid sjö- och luftradiotrafik, **13.4.1**
 - [x] Internationella nödfrekvenser, **13.4.2**
 - [x] Åtgärder då nödsignaler uppfattas, **13.4.4 –13.4.8**
 - [x] CQ Emergency, **tas inte upp då uttrycket aldrig haft stöd i ITU-RR.**
 - [x] Anropssignaler, **13.5**
 - [x] QSO och exempel, **13.5 – 13.8**
 - [x] DX, Pile-up och split, **saknas i koncept**
 - [x] Internationellt, ITUs frekvensfördelningsplan 14.1
 - [x] Regionindelning, **14.4**
 - [x] Frekvensband i Sverige, **13.12, bilaga E och F , utdragen tabell med frekvenser och effekter ur PTSFS 2015:4, saknas, bilaga F visar istället utdrag ur PTSFS 2015:3 med frekvenser och effekter.**
 - [x] Sekundär användning (allocation), **bilaga F**
 - [x] Bandplaner, **bilaga E**
 - [x] Exklusiva frekvenser för telegrafi, **bilaga E dock inte samlat på ett ställe**
 - [x] Frekvensband 430 – 440 MHz inom ITU, IARU. **Koncept endast Norden bilaga E.2**
 - [x] SSTV, **saknas**
 - [x] Semiduplex, **saknas**
 - [x] Halvduplex, **saknas**
 - [x] Simplex, **saknas**
 - [x] Brusspärr, **5.8.6**
 - [x] Tonöppning, **5.8.7**
 - [x] Hederskod, **13.9**
 - [x] CEPT, **14.2**
 - [x] T/R 61-01, **14.2.2**
 - [x] T/R 61-02, **14.2.2**
 - [x] R9 - Nationellt i Sverige, **14.3**
 - [x] LEK, **14.3.1**
 - [x] Radioutrutrustningslag, **12.2.1**
 - [x] EMC, **10.1.1**
 - [x] Du får göra följande enligt ovan nämnda lagar och förordningar, **12.2.1 dock inte vad du inte får göra**
 - [x] Yttrandefrihetsgrundlagen (1991:1469), **YGL tas inte upp i Koncept**
 - [x] Störningar förorsakade av amatörradiosändare, **10.1.2 –10.1.3**
 - [x] Begreppen Amatörradiocertifikat, amatörradiosändare och amatörradiotrafik ur PTSFS 2014:4, **saknas**

**Comment by fnadde42** [comment]
Det här är mycket viktigt att den här informationen finns i KonCEPT. Det är en av de saker som kommer på PTS provet och informationen som fanns i Bli Sändaramatör var minst sagt förvirrande.

**Comment by SM7NTJ** [comment]
Analys visar att det mesta täcks in. Några begrepp förklaras inte i Koncept.
 Internationella nödsignaler  13.4
 Nödsignaler vid sjö- och luftradiotrafik 13.4.1
 Internationella nödfrekvenser 13.4.2
Åtgärder då nödsignaler uppfattas 13.4.4 –13.4.8
CQ Emergency tas inte upp då uttrycket aldrig haft stöd i ITU-RR.
Anropssignaler 13.5
QSO  och exempel 13.5 – 13.8
DX, Pile-up och split saknas i koncept
Internationellt, ITUs frekvensfördelningsplan 14.1
Regionindelning 14.4
Frekvensband i Sverige 13.12, bilaga E och F , utdragen tabell med frekvenser och effekter ur PTSFS 2015:4 saknas, bilaga F visar istället utdrag ur PTSFS 2015:3 med frekvenser och effekter.
Sekundär användning (allocation) bilaga F
Bandplaner bilaga E
Exklusiva frekvenser för telegrafi bilaga E dock inte samlat på ett ställe
Frekvensband 430 – 440 MHz inom ITU, IARU. Koncept endast Norden bilaga E.2
SSTV saknas
Semiduplex saknas
Halvduplex saknas
Simplex saknas
Brusspärr 5.8.6
Tonöppning 5.8.7
Hederskod 13.9
CEPT 14.2
T/R 61-01 14.2.2
T/R 61-02 14.2.2
R9 - Nationellt i Sverige 14.3
LEK 14.3.1
Radioutrutrustningslag 12.2.1
EMC 10.1.1
Du får göra följande enligt ovan nämnda lagar och förordningar 12.2.1 dock inte vad du inte får göra
Yttrandefrihetsgrundlagen (1991:1469), YGL tas inte upp i Koncept
Störningar förorsakade av amatörradiosändare 10.1.2 –10.1.3
Begreppen Amatörradiocertifikat, amatörradiosändare och amatörradiotrafik ur PTSFS 2014:4 saknas

**Comment by sa0mad** [comment]
Bilaga F är nog feltolkad, eftersom den pekar på både 2015:3 och 2015:4, man behöver nämligen båda för att få den totala vyn, därför refereras även bägge, men det kan tolkas som man bara pekar på en av dem.

**Comment by sa0mad** [comment]
Granska gärna mina bidrag, men förhoppningsvis ger de lite mer kött på benen än supplementet gör.

**Comment by sa0mad** [comment]
Enligt diskussion behövs inte YGL i Koncept.

**Comment by sa0mad** [comment]
Åtgärdad
